//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmatic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_user_roles
    {
        public string id_user { get; set; }
        public string id_role { get; set; }
        public string STATUS { get; set; }
    
        public virtual auth_roles auth_roles { get; set; }
        public virtual auth_users auth_users { get; set; }
    }
}
