//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmatic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cinema_rooms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cinema_rooms()
        {
            this.cinema_functions = new HashSet<cinema_functions>();
        }
    
        public string id { get; set; }
        public string id_agency { get; set; }
        public int number_room { get; set; }
        public string title { get; set; }
        public string ubication { get; set; }
        public string description { get; set; }
        public string model { get; set; }
        public string status { get; set; }
    
        public virtual cinema_agencies cinema_agencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cinema_functions> cinema_functions { get; set; }
    }
}
