//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmatic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_deta
    {
        public int id_invoice { get; set; }
        public int line { get; set; }
        public string detail { get; set; }
        public Nullable<decimal> total_line { get; set; }
        public string status { get; set; }
    
        public virtual invoice invoice { get; set; }
    }
}
