//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmatic.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FilmaticEntities2 : DbContext
    {
        public FilmaticEntities2()
            : base("name=FilmaticEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int P_CreateUser(string lv_username, string lv_password, string lv_name, string lv_lastname, string lv_email, string lv_phone_number, string lv_id_document, Nullable<System.DateTime> lv_birthday_date)
        {
            var lv_usernameParameter = lv_username != null ?
                new ObjectParameter("Lv_username", lv_username) :
                new ObjectParameter("Lv_username", typeof(string));
    
            var lv_passwordParameter = lv_password != null ?
                new ObjectParameter("Lv_password", lv_password) :
                new ObjectParameter("Lv_password", typeof(string));
    
            var lv_nameParameter = lv_name != null ?
                new ObjectParameter("Lv_name", lv_name) :
                new ObjectParameter("Lv_name", typeof(string));
    
            var lv_lastnameParameter = lv_lastname != null ?
                new ObjectParameter("Lv_lastname", lv_lastname) :
                new ObjectParameter("Lv_lastname", typeof(string));
    
            var lv_emailParameter = lv_email != null ?
                new ObjectParameter("Lv_email", lv_email) :
                new ObjectParameter("Lv_email", typeof(string));
    
            var lv_phone_numberParameter = lv_phone_number != null ?
                new ObjectParameter("Lv_phone_number", lv_phone_number) :
                new ObjectParameter("Lv_phone_number", typeof(string));
    
            var lv_id_documentParameter = lv_id_document != null ?
                new ObjectParameter("Lv_id_document", lv_id_document) :
                new ObjectParameter("Lv_id_document", typeof(string));
    
            var lv_birthday_dateParameter = lv_birthday_date.HasValue ?
                new ObjectParameter("Lv_birthday_date", lv_birthday_date) :
                new ObjectParameter("Lv_birthday_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_CreateUser", lv_usernameParameter, lv_passwordParameter, lv_nameParameter, lv_lastnameParameter, lv_emailParameter, lv_phone_numberParameter, lv_id_documentParameter, lv_birthday_dateParameter);
        }
    }
}
